#-*- coding: utf-8 -*-
item_map = \
{'Charge': {'class': {None: 30916, 'Invalid value of charge': 30916},
            'prefix': 'Josm_',
            'tags': ['tag'],
            'url': 'https://josm.openstreetmap.de/josmfile?page=Rules/ChargeRules&rule',
            'url_display': 'https://josm.openstreetmap.de/wiki/Rules/ChargeRules'},
 'DutchSpecific': {'class': {None: 0,
                             'NL German style tagging': 90206,
                             'NL addresses and contacts': 90201,
                             'NL deprecated features': 90202,
                             'NL education': 90210,
                             'NL heritage': 90204,
                             'NL mofa tagging': 90208,
                             'NL nomenclature': 90203,
                             'NL speed limits': 90207,
                             'NL traffic signs': 90205,
                             'NL unusual values': 90209},
                   'item': 9020,
                   'only_for': ['NL-ZH',
                                'NL-ZE',
                                'NL-NB',
                                'NL-LI',
                                'NL-GE',
                                'NL-OV',
                                'NL-DR',
                                'NL-FR',
                                'NL-GR',
                                'NL-FL',
                                'NL-UT',
                                'NL-NH'],
                   'prefix': 'Josm_',
                   'subclass_blacklist': [1560886491, 1411893821],
                   'url': 'https://raw.githubusercontent.com/Famlam/OsmMapcssValidationNL/main/netherlands.validator.mapcss',
                   'url_display': 'https://github.com/Famlam/OsmMapcssValidationNL/blob/main/netherlands.validator.mapcss'},
 'FranceSpecificRules': {'class': {None: 9019007,
                                   "Unusual ref for motorway_junction; use of 'ref=*' for the exit destination ref?": 9019004,
                                   'missing tag': 9019003,
                                   'validation rules highway milestone': 9019001,
                                   'validation rules nat_ref in France': 9019002},
                         'item': 9019,
                         'only_for': ['FR'],
                         'prefix': 'Josm_',
                         'tags': [],
                         'url': 'https://josm.openstreetmap.de/josmfile?page=Rules/FranceSpecificRules',
                         'url_display': 'https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules'},
 'ItalySpecific': {'class': {None: 21001},
                   'only_for': ['IT'],
                   'prefix': 'Josm_',
                   'url': 'https://josm.openstreetmap.de/josmfile?page=Rules/ItalySpecific',
                   'url_display': 'https://josm.openstreetmap.de/wiki/Rules/ItalySpecific'},
 'Rules_Brazilian-Specific': {'class': {"''{0}'' sem ''{1}'' definida": 9018066,
                                        'Brasil - Correções e melhorias': 9018006,
                                        'Brasil - Verificar': 9018002,
                                        'SAMU classificado de forma errada': 9018016,
                                        'adicionar {0} ao {1}': 9018018,
                                        'ausência de boundary=protected_area': 9018035,
                                        'ausência de wetland=*': 9018065,
                                        'ausência do tempo de duração ({0}) da balsa': 9018027,
                                        'chave inválida: {0}': 9018022,
                                        "especificar valor correto para {0} ao invés de ''{1}''": 9018021,
                                        'nome supérfluo/incompleto de local de lazer': 9018004,
                                        'nome supérfluo/incompleto de local de saúde': 9018005,
                                        'nome utilizado de forma incorreta': 9018031,
                                        'não classificar via como {0}': 9018051,
                                        'não se deve utilizar {0} para demarcar áreas de cobertura de imagem': 9018023,
                                        "não utilizar ''{0}'' para locais sem número": 9018043,
                                        'nó não deve possuir {0}': 9018032,
                                        'o conteúdo de {0} deve fazer parte de ref, separado por ;': 9018039,
                                        'objeto com nomenclatura incorreta': 9018007,
                                        'objeto contém Google como source': 9018044,
                                        'objeto incompleto: possui apenas {0}': 9018041,
                                        'objeto incompleto: possui apenas {0} e {1}': 9018042,
                                        'objeto não deve possuir {0}': 9018017,
                                        'palavra abreviada em {0}': 9018003,
                                        'possível ausência de tag {0}': 9018026,
                                        "possível definição incorreta para praça: ''{0}''": 9018029,
                                        'relação não deve possuir {0}': 9018046,
                                        'uso incorreto de {0}': 9018064,
                                        'uso incorreto de {0} com {1}': 9018063,
                                        'utilizar prefixo em português (pt:) para {0}': 9018030,
                                        "utilize ''destination'' no caminho de saída ao invés de ''exit_to''": 9018037,
                                        'valor incorreto para {0}': 9018034,
                                        '{0} com nome supérfluo/incompleto': 9018052,
                                        '{0} com valor = {1}': 9018014,
                                        '{0} deve conter apenas o nome da cidade': 9018013,
                                        "{0} deve estar incluído em {1}, separado por '';'' caso necessário": 9018020,
                                        "{0} deve possuir ''type=boundary''": 9018048,
                                        '{0} deve possuir {1}': 9018033,
                                        '{0} deve ser usado apenas em ways': 9018036,
                                        '{0} deve ser utilizado apenas em nós': 9018047,
                                        '{0} deve ser utilizado apenas no nó de saída da rodovia': 9018056,
                                        '{0} deve ser utilizado com {1}={0} ou {2}={0}': 9018019,
                                        '{0} deve ser utilizado junto com {1}': 9018049,
                                        "{0} inapropriada para ''{1}''": 9018067,
                                        '{0} não deve possuir {1}': 9018053,
                                        '{0} não deve ser utilizado em nó; utilizar a restrição na via': 9018008,
                                        '{0} sem nome': 9018012,
                                        '{0} sem pelo menos uma das tags: {1} ou {2}': 9018010,
                                        '{0} é uma chave utilizada apenas no Reino Unido': 9018009},
                              'item': 9018,
                              'only_for': ['BR'],
                              'prefix': 'Josm_',
                              'subclass_blacklist': [339470124,
                                                     995006835,
                                                     1594044971,
                                                     226394604,
                                                     2012241162,
                                                     1322492249,
                                                     1123790420,
                                                     951501764,
                                                     1948798798,
                                                     733725137,
                                                     2074305530,
                                                     282605167,
                                                     39095837,
                                                     1154433213,
                                                     1415734409,
                                                     58812649,
                                                     1354724892,
                                                     2146320716,
                                                     1840875080,
                                                     1508736498,
                                                     877403916,
                                                     1322492249,
                                                     481849808,
                                                     1279481357,
                                                     200264401,
                                                     200264401],
                              'tags': ['tag'],
                              'url': 'https://raw.githubusercontent.com/OSMBrasil/validador-josm/master/Rules_Brazilian-Specific.validator.mapcss',
                              'url_display': 'https://github.com/OSMBrasil/validador-josm/blob/master/Rules_Brazilian-Specific.validator.mapcss'},
 'Seamark': {'class': {'In {0} {1}={2} require {3}={4}': 9012009,
                       'Multi-colour {0} without {1}': 9012001,
                       'Probably wrong category on {0}, the colour combination {1} usually mean {2}': 9012005,
                       'Probably wrong category on {0}, {1} colour mean {2} in {3}': 9012004,
                       'Unrecognized {0}: {1}': 9012002,
                       '{0} have no IALA or system defind ({1})': 9012003,
                       '{0} have no {1}': 9012006,
                       '{0} set without {1}={2}': 9012007,
                       '{0} sign require {1} set to left or right': 9012010,
                       '{0} without {1}': 9012008},
             'item': 9012,
             'prefix': 'Josm_',
             'tags': ['tag', 'seamark'],
             'url': 'https://raw.githubusercontent.com/OpenNauticalChart/josm/master/Seamark.validator.mapcss',
             'url_display': 'https://github.com/OpenNauticalChart/josm/blob/master/Seamark.validator.mapcss'},
 'SuspiciousSwimming_Pool': {'class': {None: 30801,
                                       'If this is a facility containing one or more swimming pools it should be tagged leisure=sports_centre + sport=swimming.': 30801},
                             'item': 3080,
                             'prefix': 'Josm_',
                             'tags': ['tag'],
                             'url': 'https://josm.openstreetmap.de/josmfile?page=Rules/SuspiciousSwimming_Pool',
                             'url_display': 'https://josm.openstreetmap.de/wiki/Rules/SuspiciousSwimming_Pool'},
 'addresses': {'class': {'Same value of {0} and {1}': 9000003,
                         '{0} without number': 9000004},
               'item': 9000,
               'not_for': ['CA'],
               'prefix': 'Josm_',
               'tags': ['tag', 'addr'],
               'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/addresses.mapcss?format=txt',
               'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/addresses.mapcss'},
 'combinations': {'class': {'Use {0} only as value of {1}': 9001005,
                            'incomplete usage of {0} on a way without {1}': 9001004,
                            'missing tag': 9001001,
                            'power=circuit relations should have a topology tag with value linear or branched': 9001006,
                            'suspicious tag combination': 9001002,
                            '{0} on a relation without {1}': 9001003},
                  'item': 9001,
                  'prefix': 'Josm_',
                  'subclass_blacklist': [643796350, 317760248, 110705769],
                  'tags': ['tag'],
                  'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss?format=txt',
                  'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/combinations.mapcss'},
 'de-openrailwaymap': {'class': {"German Ks signals can't have main and distant signal at the same place, try a combined signal instead": 9016009,
                                 "German distant signals can't be repeated and shortened at the same time": 9016008,
                                 'It is not possible that a main or combined signal both has a substitute signal and has no substitute signal.': 9016032,
                                 'It is unclear if Zs10 light signals have ever been placed, please double check.': 9016016,
                                 'KVB hp signals only exist as light signals': 9016003,
                                 'Ne 14 sign requires additional tag railway:signal:train_protection:type=block_marker': 9016006,
                                 'Sh light signals cannot display Sh 0, but only Hp 0': 9016011,
                                 'Sh semaphore signals cannot display Hp 0, but only Sh 0': 9016010,
                                 'Signal Gsp 2 was renamed to Wn 7 in 2008': 9016005,
                                 'Track names should be real names. KBS numbers should be mapped as a relation with route=railway, track numbers as railway:track_ref=*.': 9016024,
                                 'Track names should be real names. KBS numbers should be mapped as a relation with route=railway.': 9016023,
                                 'Track names should be real names. VzG numbers should be tagged ref=*. KBS numbers should be mapped as a relation with route=railway.': 9016022,
                                 'Track refs should be VzG numbers in Germany. KBS numbers should be mapped as a relation with route=railway, track numbers as railway:track_ref=*.': 9016026,
                                 'Track refs should be VzG numbers in Germany. KBS numbers should be mapped as a relation with route=railway.': 9016025,
                                 'Tracks should not be named by their timetable number (KBS xy). Use a route relation with route=railway, instead.': 9016017,
                                 'Vr repeated signals only exist as light signals': 9016004,
                                 'VzG numbers should be tagged as ref=* without "VzG"': 9016020,
                                 "Zs3 light signal states should have the form 'speed[;speed …][;off][;?], speeds can only be multiples of 10": 9016015,
                                 'Zs3 sign signals can only have a single speed, are a multiple of 5 and cannot be greater than 160': 9016013,
                                 "Zs3v light signal states should have the form 'speed[;speed …][;off][;?], speeds can only be multiples of 10": 9016014,
                                 'Zs3v sign signals can only have a single speed, are a multiple of 5 and cannot be greater than 160': 9016012,
                                 'hp signals only exist as semaphore or light signals': 9016002,
                                 'main and repeated distant signal usually are not at the same place': 9016007,
                                 "mapcss._tag_uncapture(capture_tags, 'workrules={1.value} is deprecated, change to workrules=DE:{1.value}')": 9016031,
                                 "mapcss._tag_uncapture(capture_tags, '{1.value} signals only exist as light signals')": 9016030,
                                 'ref=* should be a VzG number (without "VzG"). Use a route relation with route=railway for KBS numbers, instead.': 9016018,
                                 'ref=* should be a VzG number without "VzG"': 9016019,
                                 'ref=* should only be a VzG number, it should not contain the track number': 9016021,
                                 'workrules: separate country and ruleset by : , not by -': 9016029,
                                 'workrules=BOA is deprecated, replace by an adequate value': 9016028},
                       'item': 9016,
                       'only_for': ['DE'],
                       'prefix': 'Josm_',
                       'tags': ['tag', 'railway'],
                       'url': 'https://www.openrailwaymap.org/validator/de-openrailwaymap.validator.mapcss'},
 'deprecated': {'class': {"''{0}'' does not specify the official mode of transportation, use ''{1}'' for example": 9002003,
                          "''{0}'' is meaningless, use more specific tags, e.g. ''{1}''": 9002002,
                          'The key {0} has an uncommon value.': 9002017,
                          'Unusual key {0}, maybe {1} or {2} is meant': 9002021,
                          'Wrong usage of {0} tag. Remove {1}, because it is clear that the name is missing even without an additional tag.': 9002005,
                          'deprecated tagging': 9002001,
                          'misspelled value': 9002018,
                          'questionable key (ending with a number)': 9002014,
                          'uncommon short key': 9002012,
                          'unusual value of {0}': 9002020,
                          'wrong value: {0}': 9002019,
                          '{0} is not recommended. Use the Reverse Ways function from the Tools menu.': 9002016,
                          '{0} is unspecific': 9002024,
                          '{0} is unspecific. Instead use the key fixme with the information what exactly should be fixed in the value of fixme.': 9002006,
                          '{0} with a temporary URL which may be outdated very soon': 9002023,
                          "{0}={1} is unspecific. Instead of ''{1}'' please give more information about what exactly should be fixed.": 9002004,
                          "{0}={1} is unspecific. Please replace ''{1}'' by a specific value.": 9002007},
                'item': 9002,
                'prefix': 'Josm_',
                'subclass_blacklist': [740601387,
                                       1157046268,
                                       1195531951,
                                       590643159,
                                       1089331760,
                                       1116761280,
                                       1752615188,
                                       1052866123,
                                       1825345743,
                                       690512681,
                                       1008752382,
                                       2085280194,
                                       1341786818,
                                       847809313,
                                       2012807801,
                                       1450116742,
                                       213844674,
                                       1538706366,
                                       30762614,
                                       423232686,
                                       693675339,
                                       512779280,
                                       52025933,
                                       1423074682,
                                       306662985,
                                       707111885,
                                       294264920,
                                       719234223,
                                       1850270072,
                                       1064658218,
                                       1562207150,
                                       1376789416,
                                       532391183,
                                       796960259,
                                       1319611546,
                                       2027311706,
                                       1696784412,
                                       967497433,
                                       1034538127,
                                       563629665,
                                       1582968978,
                                       297159061,
                                       2041296832,
                                       1115157097,
                                       1959365145,
                                       595008939,
                                       1108230656,
                                       1768681881,
                                       94558529,
                                       1047428067,
                                       1785584789,
                                       651933474,
                                       1878458659,
                                       1968473048,
                                       1331930630,
                                       2075099676,
                                       2091877281,
                                       728429076,
                                       634698090,
                                       967271828,
                                       426261497,
                                       192707176,
                                       954237438,
                                       1751915206,
                                       905310794,
                                       647435126,
                                       1317841090,
                                       1435678043,
                                       765169083,
                                       1966772390,
                                       20631498,
                                       469903103,
                                       1459865523,
                                       1844620979,
                                       34751027,
                                       904750343,
                                       596668979,
                                       1675828779,
                                       1681273585,
                                       1007567078,
                                       1061429000,
                                       1503278830,
                                       1282397509,
                                       1463909830,
                                       1531788430,
                                       1957125311,
                                       591931361,
                                       1305128315,
                                       145760951,
                                       488242503,
                                       1861188094,
                                       50459238,
                                       430042074,
                                       1600840641,
                                       881828009],
                'tags': ['tag', 'deprecated'],
                'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/deprecated.mapcss?format=txt',
                'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/deprecated.mapcss'},
 'geometry': {'class': {'Object at Position 0.00E 0.00N. There is nothing at this position except an already mapped weather buoy.': 9003009,
                        'missing tag': 9003014,
                        '{0} is the tag for the linear waterway. To tag the water area use {1} + {2} instead.': 9003013,
                        '{0} on a closed way. Should be used on an unclosed way.': 9003011,
                        '{0} on a node': 9003006,
                        '{0} on a node. Should be drawn as an area.': 9003003,
                        '{0} on a node. Should be used in a relation': 9003004,
                        '{0} on a node. Should be used on a way or relation.': 9003002,
                        '{0} on a node. Should be used on a way.': 9003001,
                        '{0} on a relation': 9003012,
                        '{0} on a way. Should be used in a relation': 9003008,
                        '{0} on a way. Should be used on a node.': 9003007},
              'item': 9003,
              'prefix': 'Josm_',
              'tags': ['geom'],
              'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/geometry.mapcss?format=txt',
              'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/geometry.mapcss'},
 'highway': {'class': {'Unspecific highway type': 9004004,
                       'abbreviated street name': 9004001,
                       'deprecated tagging': 9004006,
                       'missing tag': 9004009,
                       'questionable value (ending with a number)': 9004012,
                       'suspicious tag combination': 9004011,
                       'unusual value of {0}': 9004014,
                       'wrong crossing tag on a way': 9004002,
                       'wrong highway tag on a node': 9004008,
                       '{0} on a node': 9004010,
                       '{0} together with {1}': 9004013},
             'item': 9004,
             'prefix': 'Josm_',
             'tags': ['tag', 'highway'],
             'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/highway.mapcss?format=txt',
             'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/highway.mapcss'},
 'multiple': {'class': {"empty value in semicolon-separated ''{0}''": 9005002,
                        '{0} with multiple values': 9005001},
              'item': 9005,
              'prefix': 'Josm_',
              'tags': ['tag', 'value'],
              'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/multiple.mapcss?format=txt',
              'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/multiple.mapcss'},
 'numeric': {'class': {'Airport tagging': 9006022,
                       'Definition of {0} is unclear': 9006027,
                       'Unnecessary amount of decimal places': 9006021,
                       'Unusually large value of {0}, possibly centimeter units are meant?': 9006033,
                       'imprecise value of {0}': 9006029,
                       'negative {0} value': 9006023,
                       'numerical key': 9006001,
                       'suspicious tag combination': 9006030,
                       'unnecessary tag': 9006025,
                       'unusual value of {0}': 9006010,
                       'unusual value of {0}: meters is default; only positive values; point is decimal separator; if units, put space then unit': 9006032,
                       'unusual value of {0}: set unit e.g. {1} or {2}; only positive values; point is decimal separator; space between value and unit': 9006028,
                       'unusual value of {0}: use \'\' for foot and " for inches, no spaces': 9006031,
                       'unusual value of {0}: use . instead of , as decimal separator': 9006017,
                       'unusual value of {0}: use abbreviation for unit and space between value and unit': 9006024,
                       'unusual value of {0}: {1} is default; only positive values; point is decimal separator; if units, put space then unit': 9006026,
                       'voltage should be in volts with no units/delimiter/spaces': 9006013,
                       '{0} must be a numeric value': 9006008,
                       '{0} must be a numeric value, in meters and without units': 9006011,
                       '{0} must be a positive integer number': 9006009,
                       '{0} should be an integer value between -5 and 5': 9006003,
                       '{0} should have numbers only with optional .5 increments': 9006004,
                       '{0} value with + sign': 9006002},
             'item': 9006,
             'prefix': 'Josm_',
             'tags': ['tag', 'value'],
             'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/numeric.mapcss?format=txt',
             'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/numeric.mapcss'},
 'openrailwaymap': {'class': {'A sign cannot have different states.': 9015031,
                              'Crossings and level crossings should be mapped as nodes': 9015017,
                              'If tracks are tagged with service=*, they should be mapped as one way per track.': 9015016,
                              'Italian (distant) speed signal 1R/2R/3R has wrong number of speeds.': 9015048,
                              'Key traffic_mode is deprecated': 9015004,
                              'Milestone without position, add railway:position=*': 9015028,
                              'Station mapped as a way, but should be mapped as a node': 9015002,
                              'Tagging for resetting switch is deprecated, change railway:switch=* to proper value': 9015040,
                              'Track tagged with usage=* AND service=* - remove one of these tags': 9015001,
                              'Wrong tag for railway station building': 9015046,
                              'controlled_area relations are deprecated': 9015041,
                              'interlocking relation with type other than railway': 9015043,
                              'interlocking relation without type=railway': 9015042,
                              'lanes=* is used for highways, not railways': 9015024,
                              'main and combined signal at the same place': 9015035,
                              'maxspeed should contain the value as it is shown on the line with mph as unit': 9015026,
                              'maxspeed=signals is deprecated, tag the highest possible speed instead': 9015025,
                              "platform names or refs should not include the word 'track', write that as 'description', put the bare numbers in 'ref', separated by ';'": 9015010,
                              'platforms should have the numbers in ref, not railway:track_ref': 9015008,
                              'power:type is deprecated, change to proper electrified value': 9015013,
                              'power:type=overhead is deprecated': 9015011,
                              'power:type=overhead is deprecated, conflict between {0} and {1}': 9015012,
                              'priority on railway objects is deprecated, remove it': 9015014,
                              'radio=* is deprecated, change to proper railway:radio value': 9015019,
                              'radio=GSM-R is deprecated': 9015018,
                              'railway:signal:stop:description is deprecated and has been replaced by railway:signal:stop:caption': 9015033,
                              'railway:signal:stop:description is deprecated, replace by appropiate railway:signal:stop:caption value': 9015034,
                              'railway=flat_crossing is deprecated': 9015032,
                              'signal names should be prefixed with an operator or country prefix': 9015038,
                              'signal specification given but node is not tagged as signal or equivalent type': 9015030,
                              'signals should be tagged with ref, not railway:ref': 9015036,
                              'signals should have a railway:signal:direction=* tag': 9015037,
                              "track names or refs should not include the word 'track', tag those numbers as railway:track_ref": 9015009,
                              'track numbers inside a station should be railway:track_ref, not name': 9015007,
                              'track numbers inside a station should be railway:track_ref, not ref': 9015045,
                              "track tagged with 'bridge' in name, consider using bridge:name instead and put the track name into name": 9015022,
                              "track tagged with 'bridge' in wikipedia, consider using bridge:wikipedia instead and put track wikipedia entry into wikipedia": 9015023,
                              "track tagged with 'tunnel' in name, consider using tunnel:name instead and put the track name into name": 9015020,
                              "track tagged with 'tunnel' in wikipedia, consider using tunnel:wikipedia instead and put the track wikipedia entry into wikipedia": 9015021,
                              'tracks=1 not necessary if detail=track is tagged.': 9015015,
                              'usage=freight is deprecated': 9015005,
                              'workrules should be used on ways and not on nodes.': 9015047,
                              '{0} identification should be tagged as ref, not as name': 9015039,
                              '{0}={1} without name': 9015044},
                    'item': 9015,
                    'prefix': 'Josm_',
                    'subclass_blacklist': [160705788, 321695123],
                    'tags': ['tag', 'railway'],
                    'url': 'https://www.openrailwaymap.org/validator/openrailwaymap.validator.mapcss'},
 'powerQA': {'class': {'Incompatibility between method and source on a power generator': 7040006,
                       'Incompatibility between method and source on a power plant': 7040022,
                       'Invalid voltage value for this country (Afghanistan)': 7040036,
                       'Invalid voltage value for this country (Albania)': 7040037,
                       'Invalid voltage value for this country (Algeria)': 7040038,
                       'Invalid voltage value for this country (Andorra)': 7040039,
                       'Invalid voltage value for this country (Angola)': 7040040,
                       'Invalid voltage value for this country (Argentina)': 7040041,
                       'Invalid voltage value for this country (Armenia)': 7040042,
                       'Invalid voltage value for this country (Australia)': 7040043,
                       'Invalid voltage value for this country (Austria)': 7040044,
                       'Invalid voltage value for this country (Azerbaijan)': 7040045,
                       'Invalid voltage value for this country (Bahrain)': 7040046,
                       'Invalid voltage value for this country (Bangladesh)': 7040047,
                       'Invalid voltage value for this country (Belarus)': 7040048,
                       'Invalid voltage value for this country (Belgium)': 7040049,
                       'Invalid voltage value for this country (Belize)': 7040050,
                       'Invalid voltage value for this country (Benin)': 7040051,
                       'Invalid voltage value for this country (Bhutan)': 7040052,
                       'Invalid voltage value for this country (Bolivia)': 7040053,
                       'Invalid voltage value for this country (Bosnia and Herzegovina)': 7040054,
                       'Invalid voltage value for this country (Botswana)': 7040055,
                       'Invalid voltage value for this country (Brazil)': 7040056,
                       'Invalid voltage value for this country (Brunei)': 7040057,
                       'Invalid voltage value for this country (Bulgaria)': 7040058,
                       'Invalid voltage value for this country (Burkina Faso)': 7040059,
                       'Invalid voltage value for this country (Burundi)': 7040060,
                       'Invalid voltage value for this country (Cambodia)': 7040061,
                       'Invalid voltage value for this country (Cameroon)': 7040062,
                       'Invalid voltage value for this country (Canada)': 7040063,
                       'Invalid voltage value for this country (Cape Verde)': 7040064,
                       'Invalid voltage value for this country (Central African Republic)': 7040065,
                       'Invalid voltage value for this country (Chad)': 7040066,
                       'Invalid voltage value for this country (Chile)': 7040067,
                       'Invalid voltage value for this country (Colombia)': 7040068,
                       'Invalid voltage value for this country (Costa Rica)': 7040069,
                       'Invalid voltage value for this country (Croatia)': 7040070,
                       'Invalid voltage value for this country (Cuba)': 7040071,
                       'Invalid voltage value for this country (Cyprus)': 7040072,
                       'Invalid voltage value for this country (Czech Republic)': 7040073,
                       'Invalid voltage value for this country (Democratic Republic of the Congo)': 7040074,
                       'Invalid voltage value for this country (Djibouti)': 7040075,
                       'Invalid voltage value for this country (Dominican Republic)': 7040076,
                       'Invalid voltage value for this country (Ecuador)': 7040077,
                       'Invalid voltage value for this country (Egypt)': 7040078,
                       'Invalid voltage value for this country (El Salvador)': 7040079,
                       'Invalid voltage value for this country (Equatorial Guinea)': 7040080,
                       'Invalid voltage value for this country (Eritrea)': 7040081,
                       'Invalid voltage value for this country (Estonia)': 7040082,
                       'Invalid voltage value for this country (Eswatini)': 7040083,
                       'Invalid voltage value for this country (Ethiopia)': 7040084,
                       'Invalid voltage value for this country (Federated States of Micronesia)': 7040085,
                       'Invalid voltage value for this country (Fiji)': 7040086,
                       'Invalid voltage value for this country (Finland)': 7040087,
                       'Invalid voltage value for this country (France)': 7040088,
                       'Invalid voltage value for this country (Gabon)': 7040089,
                       'Invalid voltage value for this country (Georgia)': 7040090,
                       'Invalid voltage value for this country (Germany)': 7040091,
                       'Invalid voltage value for this country (Ghana)': 7040092,
                       'Invalid voltage value for this country (Greece)': 7040093,
                       'Invalid voltage value for this country (Guatemala)': 7040094,
                       'Invalid voltage value for this country (Guinea)': 7040095,
                       'Invalid voltage value for this country (Guinea-Bissau)': 7040096,
                       'Invalid voltage value for this country (Haiti)': 7040097,
                       'Invalid voltage value for this country (Honduras)': 7040098,
                       'Invalid voltage value for this country (Hungary)': 7040099,
                       'Invalid voltage value for this country (Iceland)': 7040100,
                       'Invalid voltage value for this country (India)': 7040101,
                       'Invalid voltage value for this country (Indonesia)': 7040102,
                       'Invalid voltage value for this country (Iran)': 7040103,
                       'Invalid voltage value for this country (Iraq)': 7040104,
                       'Invalid voltage value for this country (Ireland)': 7040105,
                       'Invalid voltage value for this country (Israel)': 7040106,
                       'Invalid voltage value for this country (Italy)': 7040107,
                       'Invalid voltage value for this country (Ivory Coast)': 7040108,
                       'Invalid voltage value for this country (Jamaica)': 7040109,
                       'Invalid voltage value for this country (Japan)': 7040110,
                       'Invalid voltage value for this country (Jordan)': 7040111,
                       'Invalid voltage value for this country (Kazakhstan)': 7040112,
                       'Invalid voltage value for this country (Kenya)': 7040113,
                       'Invalid voltage value for this country (Kingdom of Denmark)': 7040114,
                       'Invalid voltage value for this country (Kingdom of the Netherlands)': 7040115,
                       'Invalid voltage value for this country (Kuwait)': 7040116,
                       'Invalid voltage value for this country (Kyrgyzstan)': 7040117,
                       'Invalid voltage value for this country (Laos)': 7040118,
                       'Invalid voltage value for this country (Latvia)': 7040119,
                       'Invalid voltage value for this country (Lebanon)': 7040120,
                       'Invalid voltage value for this country (Lesotho)': 7040121,
                       'Invalid voltage value for this country (Liberia)': 7040122,
                       'Invalid voltage value for this country (Libya)': 7040123,
                       'Invalid voltage value for this country (Liechtenstein)': 7040124,
                       'Invalid voltage value for this country (Lithuania)': 7040125,
                       'Invalid voltage value for this country (Luxembourg)': 7040126,
                       'Invalid voltage value for this country (Madagascar)': 7040127,
                       'Invalid voltage value for this country (Malawi)': 7040128,
                       'Invalid voltage value for this country (Malaysia)': 7040129,
                       'Invalid voltage value for this country (Maldives)': 7040130,
                       'Invalid voltage value for this country (Mali)': 7040131,
                       'Invalid voltage value for this country (Malta)': 7040132,
                       'Invalid voltage value for this country (Mauritania)': 7040133,
                       'Invalid voltage value for this country (Mauritius)': 7040134,
                       'Invalid voltage value for this country (Mexico)': 7040135,
                       'Invalid voltage value for this country (Moldova)': 7040136,
                       'Invalid voltage value for this country (Mongolia)': 7040137,
                       'Invalid voltage value for this country (Montenegro)': 7040138,
                       'Invalid voltage value for this country (Morocco)': 7040139,
                       'Invalid voltage value for this country (Mozambique)': 7040140,
                       'Invalid voltage value for this country (Myanmar)': 7040141,
                       'Invalid voltage value for this country (Namibia)': 7040142,
                       'Invalid voltage value for this country (Nepal)': 7040143,
                       'Invalid voltage value for this country (New Zealand)': 7040144,
                       'Invalid voltage value for this country (Nicaragua)': 7040145,
                       'Invalid voltage value for this country (Niger)': 7040146,
                       'Invalid voltage value for this country (Nigeria)': 7040147,
                       'Invalid voltage value for this country (North Korea)': 7040148,
                       'Invalid voltage value for this country (North Macedonia)': 7040149,
                       'Invalid voltage value for this country (Norway)': 7040150,
                       'Invalid voltage value for this country (Oman)': 7040151,
                       'Invalid voltage value for this country (Pakistan)': 7040152,
                       'Invalid voltage value for this country (Panama)': 7040153,
                       'Invalid voltage value for this country (Papua New Guinea)': 7040154,
                       'Invalid voltage value for this country (Paraguay)': 7040155,
                       "Invalid voltage value for this country (People's Republic of China)": 7040156,
                       'Invalid voltage value for this country (Peru)': 7040157,
                       'Invalid voltage value for this country (Philippines)': 7040158,
                       'Invalid voltage value for this country (Poland)': 7040159,
                       'Invalid voltage value for this country (Portugal)': 7040160,
                       'Invalid voltage value for this country (Qatar)': 7040161,
                       'Invalid voltage value for this country (Republic of the Congo)': 7040162,
                       'Invalid voltage value for this country (Romania)': 7040163,
                       'Invalid voltage value for this country (Russia)': 7040164,
                       'Invalid voltage value for this country (Rwanda)': 7040165,
                       'Invalid voltage value for this country (San Marino)': 7040166,
                       'Invalid voltage value for this country (Saudi Arabia)': 7040167,
                       'Invalid voltage value for this country (Senegal)': 7040168,
                       'Invalid voltage value for this country (Serbia)': 7040169,
                       'Invalid voltage value for this country (Sierra Leone)': 7040170,
                       'Invalid voltage value for this country (Singapore)': 7040171,
                       'Invalid voltage value for this country (Slovakia)': 7040172,
                       'Invalid voltage value for this country (Slovenia)': 7040173,
                       'Invalid voltage value for this country (South Africa)': 7040174,
                       'Invalid voltage value for this country (South Korea)': 7040175,
                       'Invalid voltage value for this country (South Sudan)': 7040176,
                       'Invalid voltage value for this country (Spain)': 7040177,
                       'Invalid voltage value for this country (Sri Lanka)': 7040178,
                       'Invalid voltage value for this country (State of Palestine)': 7040179,
                       'Invalid voltage value for this country (Sudan)': 7040180,
                       'Invalid voltage value for this country (Suriname)': 7040181,
                       'Invalid voltage value for this country (Sweden)': 7040182,
                       'Invalid voltage value for this country (Switzerland)': 7040183,
                       'Invalid voltage value for this country (Syria)': 7040184,
                       'Invalid voltage value for this country (Taiwan)': 7040185,
                       'Invalid voltage value for this country (Tajikistan)': 7040186,
                       'Invalid voltage value for this country (Tanzania)': 7040187,
                       'Invalid voltage value for this country (Thailand)': 7040188,
                       'Invalid voltage value for this country (The Bahamas)': 7040189,
                       'Invalid voltage value for this country (The Gambia)': 7040190,
                       'Invalid voltage value for this country (Timor-Leste)': 7040191,
                       'Invalid voltage value for this country (Togo)': 7040192,
                       'Invalid voltage value for this country (Trinidad and Tobago)': 7040193,
                       'Invalid voltage value for this country (Tunisia)': 7040194,
                       'Invalid voltage value for this country (Turkey)': 7040195,
                       'Invalid voltage value for this country (Turkmenistan)': 7040196,
                       'Invalid voltage value for this country (Uganda)': 7040197,
                       'Invalid voltage value for this country (Ukraine)': 7040198,
                       'Invalid voltage value for this country (United Arab Emirates)': 7040199,
                       'Invalid voltage value for this country (United Kingdom)': 7040200,
                       'Invalid voltage value for this country (United States)': 7040201,
                       'Invalid voltage value for this country (Uruguay)': 7040202,
                       'Invalid voltage value for this country (Uzbekistan)': 7040203,
                       'Invalid voltage value for this country (Venezuela)': 7040204,
                       'Invalid voltage value for this country (Vietnam)': 7040205,
                       'Invalid voltage value for this country (Yemen)': 7040206,
                       'Invalid voltage value for this country (Zambia)': 7040207,
                       'Invalid voltage value for this country (Zimbabwe)': 7040208,
                       'Is it a power circuit or a power line section? Add the power=* tag accordingly.': 7040209,
                       'Unsuitable method for biofuel generator': 7040014,
                       'Unsuitable method for biofuel power plant': 7040030,
                       'Unsuitable method for biogas generator': 7040015,
                       'Unsuitable method for biogas power plant': 7040031,
                       'Unsuitable method for biomass generator': 7040013,
                       'Unsuitable method for biomass power plant': 7040029,
                       'Unsuitable method for coal generator': 7040011,
                       'Unsuitable method for coal power plant': 7040027,
                       'Unsuitable method for diesel generator': 7040017,
                       'Unsuitable method for diesel power plant': 7040033,
                       'Unsuitable method for gas generator': 7040012,
                       'Unsuitable method for gas power plant': 7040028,
                       'Unsuitable method for gasoline generator': 7040018,
                       'Unsuitable method for gasoline power plant': 7040034,
                       'Unsuitable method for hydro generator': 7040008,
                       'Unsuitable method for hydro power plant': 7040024,
                       'Unsuitable method for nuclear generator': 7040005,
                       'Unsuitable method for nuclear power plant': 7040021,
                       'Unsuitable method for oil generator': 7040016,
                       'Unsuitable method for oil power plant': 7040032,
                       'Unsuitable method for solar generator': 7040010,
                       'Unsuitable method for solar power plant': 7040026,
                       'Unsuitable method for tidal generator': 7040009,
                       'Unsuitable method for tidal power plant': 7040025,
                       'Unsuitable method for waste generator': 7040019,
                       'Unsuitable method for waste power plant': 7040035,
                       'Unsuitable method for wind generator': 7040007,
                       'Unsuitable method for wind power plant': 7040023,
                       'Unsuitable value for generator:source=* tag': 7040004,
                       'Unsuitable value for plant:source=* tag': 7040020,
                       'Unsuitable value for power=* tag': 7040002,
                       'Unsuitable value for transformer=* tag': 7040003,
                       'generator:output:electricity value has invalid format': 7040214,
                       'plant:output:electricity value has invalid format': 7040212,
                       'plant:storage value has invalid format': 7040213,
                       'power=circuit relations should have a topology tag with value linear or branched': 7040210,
                       'wires tag should be on the power line and not on the circuit relation': 7040211},
             'item': 7040,
             'prefix': 'Josm_',
             'tags': ['tag', 'power'],
             'url': 'https://raw.githubusercontent.com/open-energy-transition/validate-my-grid/refs/heads/gh-pages/powerQA.validator.mapcss',
             'url_display': 'https://github.com/open-energy-transition/validate-my-grid/blob/gh-pages/powerQA.validator.mapcss'},
 'relation': {'class': {'Power relation misses or combined to wrong power=* value': 9007002,
                        'missing tag': 9007001},
              'item': 9007,
              'prefix': 'Josm_',
              'subclass_blacklist': [1457279320],
              'tags': ['tag', 'relation'],
              'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/relation.mapcss?format=txt',
              'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/relation.mapcss'},
 'religion': {'class': {'{0}': 9008005},
              'item': 9008,
              'prefix': 'Josm_',
              'tags': ['tag'],
              'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/religion.mapcss?format=txt',
              'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/religion.mapcss'},
 'ru-housenumber': {'class': {'Номера домов не соответствующие принятому соглашению': 9017001},
                    'item': 9017,
                    'only_for': ['RU'],
                    'prefix': 'Josm_',
                    'tags': ['tag', 'addr'],
                    'url': 'https://raw.githubusercontent.com/zetx16/Josm-HnumbValidator/master/ru-housenumber.validator.mapcss',
                    'url_display': 'https://github.com/zlant/Josm-HnumbValidator/blob/master/ru-housenumber.validator.mapcss'},
 'territories': {'class': {'deprecated tagging': 9009001,
                           'street name contains ss': 9009002,
                           'street name contains ß': 9009003},
                 'item': 9009,
                 'prefix': 'Josm_',
                 'tags': ['tag'],
                 'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/territories.mapcss?format=txt',
                 'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/territories.mapcss'},
 'transport': {'class': {None: 21412,
                         'A bus stop is supposed to be a node': 9014019,
                         'Check if the note can be deleted': 9014006,
                         'Check the network tag : this network does not exist, it may be a typo': 9014026,
                         'Check the operator tag : this operator does not exist, it may be a typo': 9014025,
                         'Is it a bus stop or a bus station?': 9014002,
                         'Missing interval tag to specify the main interval': 9014023,
                         'Missing opening_hours tag': 9014024,
                         'Missing transportation mode, add a tag route = bus/coach/tram/etc': 9014009,
                         'Missing transportation mode, change tag route to route_master': 9014010,
                         'Subway entrances should be mapped as nodes': 9014027,
                         'The color of the public transport line should be in a colour tag': 9014020,
                         'The duration is invalid (try a number of minutes)': 9014022,
                         'The interval is invalid (try a number of minutes)': 9014021,
                         'The line variant does not belong to any line, add it to the route_master relation': 9014028,
                         'The network should be on the transport lines and not on the stops': 9014007,
                         'The operator should be on the transport lines and not on the stops': 9014008},
               'item': 9014,
               'prefix': 'Josm_',
               'tags': ['tag', 'public_transport'],
               'url': 'https://raw.githubusercontent.com/Jungle-Bus/transport_mapcss/master/transport.validator.mapcss',
               'url_display': 'https://github.com/Jungle-Bus/transport_mapcss/blob/master/transport.validator.mapcss'},
 'unnecessary': {'class': {'descriptive name': 9010003,
                           'unnecessary tag': 9010001,
                           '{0} makes no sense': 9010002},
                 'item': 9010,
                 'prefix': 'Josm_',
                 'tags': ['tag'],
                 'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/unnecessary.mapcss?format=txt',
                 'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/unnecessary.mapcss'},
 'wikipedia': {'class': {"''{0}'' tag is set, but no ''{1}'' tag. Make sure to set ''wikipedia=language:value'' for the main article and optional ''wikipedia:language=value'' only for additional articles that are not just other language variants of the main article.": 9011015,
                         'deprecated tagging': 9011003,
                         'wikidata tag must be in Qnnnn format, where n is a digit': 9011012,
                         "wikipedia ''{0}'' language is invalid, use ''{1}'' instead": 9011005,
                         "wikipedia ''{0}'' language is obsolete, use ''{1}'' instead": 9011004,
                         'wikipedia language seems to be duplicated, e.g. en:en:Foo': 9011011,
                         'wikipedia page title should have first letter capitalized': 9011009,
                         "wikipedia page title should have spaces instead of underscores (''_''→'' '')": 9011010,
                         'wikipedia tag has an unknown language prefix': 9011002,
                         "wikipedia tag has no language given, use ''wikipedia''=''language:page title''": 9011001,
                         "wikipedia title should not have ''{0}'' prefix": 9011008,
                         'wikipedia title should not start with a space after language code': 9011007,
                         "{0} tag should not have URL-encoded values like ''%27''": 9011006,
                         '{0} value looks like a {1} value': 9011016},
               'item': 9011,
               'prefix': 'Josm_',
               'tags': ['tag', 'wikipedia'],
               'url': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/wikipedia.mapcss?format=txt',
               'url_display': 'https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/wikipedia.mapcss'}}
